/* src/app/pages/services-page/services-content.ts */

/**
 * @file Aus dem aktiven Portfolio ausgelagerte Inhalte der bisherigen Leistungsroute.
 * @description Bewahrt die bestehende DE/EN-Angebotsbasis als bewusst isolierten Handoff für Phase 2 auf.
 * Die Daten werden nicht mehr über den öffentlichen Portfolio-Content oder das Portfolio-Routing ausgeliefert.
 */

import { PricingContent } from '../../core/models/portfolio.models';

/** Vollständige, zweisprachige Ausgangsbasis der späteren Studio-/Firmenwebsite. */
export const SERVICES_TRANSLATIONS: Record<'de' | 'en', PricingContent> = {
  de: {
      metaTitle: 'Leistungen & Preise | Webdesign, Web-Apps & Automatisierung | B²',
      metaDescription: 'Websites, Webpräsenzen und individuelle Business-Apps von B²: klare Einstiegsmodelle, SEO und Accessibility inklusive sowie optionale Pflege nach dem Launch.',
      eyebrow: 'services.exe',
      title: 'Nicht jedes Problem braucht eine App. Aber jedes Projekt die richtige Lösung.',
      subtitle: 'Digitale Lösungen, die Sichtbarkeit schaffen, Abläufe vereinfachen und manuelle Arbeit reduzieren.',
      heroPrimaryCtaLabel: 'Lösungen ansehen',
      heroSecondaryCtaLabel: 'Projekt besprechen',
      heroDialogCloseLabel: 'Scope-Dialog schließen',
      offersEyebrow: 'solutions.loaded',
      offersTitle: 'Drei Einstiege. Ein Prinzip: passend zum Ziel.',
      offersSubtitle: 'Drei Einstiegspunkte mit unterschiedlichem Fokus – je nachdem, was dein Projekt erreichen und leisten soll.',
      offersCtaLabel: 'Projekt kurz besprechen',
      qualityBaseline: 'SEO + Accessibility immer inklusive.',
      note: 'Die Projektpreise dienen als Orientierung. Umfang, Funktionen, Inhalte und technische Tiefe bestimmen den tatsächlichen Aufwand.',
      ariaLabel: 'Lösungen und Einstiegspreise für digitale Projekte',
      supportTitle: 'maintenance.mode',
      supportHeadline: 'Launch complete. System bleibt online.',
      supportText: 'Optional können Pflege, kleine Weiterentwicklungen und technische Checks übernommen werden – passend dazu, wie aktiv das Projekt weitergeführt werden soll.',
      supportCtaLabel: 'Pflege & Weiterentwicklung anfragen',
      outroEyebrow: 'next_project.exe',
      outroTitle: 'Die nächste Idee darf gern deine sein.',
      outroText: 'Ich freue mich auf Projekte, bei denen Gestaltung, Technik und ein echtes Ziel zusammenkommen. Wenn du schon eine Idee, ein Problem oder einfach einen ersten Gedanken hast: Lass uns darüber sprechen.',
      outroPrimaryCtaLabel: 'Projekt besprechen',
      outroSecondaryCtaLabel: 'Case Studies ansehen',
      outroStatus: 'connection.ready --next-project',
      supportPlans: [
        { name: 'Basic Care', price: '15 € / Monat', text: 'Kleine Text- oder Bildänderungen und ein kurzer technischer Monatscheck.' },
        { name: 'Content Care', price: '39 € / Monat', text: 'Regelmäßige Inhaltsupdates, kleine Layoutanpassungen und Pflege wichtiger SEO-Snippets.' },
        { name: 'Priority Care', price: '79 € / Monat', text: 'Priorisierte kleinere Änderungen, Monitoring-Checks und kurze technische Beratung.' },
      ],
      cards: [
        {
          title: 'Starter Website',
          price: 'ab 500 €',
          claim: 'Schnell sichtbar. Klar auf den Punkt.',
          description: 'Für einzelne Angebote, Kampagnen oder kompakte Webauftritte, bei denen eine klare Botschaft wichtiger ist als unnötiger Umfang.',
          command: 'web --landing --responsive --fast',
          features: ['Kompakter Onepager oder zielgerichtete Landingpage', 'Eigenständiges Responsive Design statt Standardvorlage', 'Schneller, sauberer technischer Aufbau'],
          ctaLabel: 'Projekt anfragen',
        },
        {
          title: 'Webpräsenz',
          price: 'ab 950 €',
          badge: 'Empfohlen',
          featured: true,
          claim: 'Gefunden werden ist nur der Anfang.',
          description: 'Für Unternehmen und Marken, die Vertrauen aufbauen, Nutzer führen und aus Aufmerksamkeit echte Anfragen machen wollen.',
          command: 'web --brand --content --conversion',
          features: ['Durchdachte Struktur für Leistungen, Inhalte und Kontakt', 'Visuelles System passend zu Marke und Zielgruppe', 'Nutzerführung für mehr Engagement und Conversion'],
          ctaLabel: 'Webpräsenz planen',
        },
        {
          title: 'Business App',
          price: 'ab 1.650 €',
          claim: 'Wenn Software anfangen soll, Arbeit abzunehmen.',
          description: 'Für interne Tools, Dashboards und individuelle Webanwendungen, die reale Prozesse digital abbilden oder automatisieren.',
          command: 'app --data --roles --automation',
          features: ['Interfaces für echte Arbeitsabläufe statt Demo-Screens', 'Rollen, Formulare, Daten, APIs und Automatisierungen', 'Wartbare Architektur für Funktionen, die wachsen dürfen'],
          ctaLabel: 'Anwendung besprechen',
        },
      ],
    },
  en: {
      metaTitle: 'Services & Pricing | Web Design, Web Apps & Automation | B²',
      metaDescription: 'Websites, web presences and custom business apps by B²: clear starting points, SEO and accessibility included, plus optional maintenance after launch.',
      eyebrow: 'services.exe',
      title: 'Not every problem needs an app. But every project needs the right solution.',
      subtitle: 'Digital solutions built to increase visibility, simplify workflows and reduce manual work.',
      heroPrimaryCtaLabel: 'Explore solutions',
      heroSecondaryCtaLabel: 'Discuss a project',
      heroDialogCloseLabel: 'Close scope dialog',
      offersEyebrow: 'solutions.loaded',
      offersTitle: 'Three starting points. One principle: fit the goal.',
      offersSubtitle: 'Three starting points with different priorities – depending on what your project needs to achieve and deliver.',
      offersCtaLabel: 'Discuss your project',
      qualityBaseline: 'SEO + accessibility always included.',
      note: 'Project prices are intended as orientation. Scope, functionality, content and technical depth determine the actual effort.',
      ariaLabel: 'Solutions and starting prices for digital projects',
      supportTitle: 'maintenance.mode',
      supportHeadline: 'Launch complete. System stays online.',
      supportText: 'Maintenance, small improvements and technical checks can be added depending on how actively the project needs to evolve.',
      supportCtaLabel: 'Request maintenance & improvements',
      outroEyebrow: 'next_project.exe',
      outroTitle: 'The next idea could be yours.',
      outroText: 'I enjoy projects where design, technology and a real objective come together. If you already have an idea, a problem or simply a first thought, let\'s talk about it.',
      outroPrimaryCtaLabel: 'Discuss a project',
      outroSecondaryCtaLabel: 'Explore case studies',
      outroStatus: 'connection.ready --next-project',
      supportPlans: [
        { name: 'Basic Care', price: '€15 / month', text: 'Small text or image changes and a short monthly technical check.' },
        { name: 'Content Care', price: '€39 / month', text: 'Regular content updates, minor layout adjustments and maintenance of important SEO snippets.' },
        { name: 'Priority Care', price: '€79 / month', text: 'Prioritized small changes, monitoring checks and short technical consulting.' },
      ],
      cards: [
        {
          title: 'Starter Website',
          price: 'from €500',
          claim: 'Visible fast. Straight to the point.',
          description: 'For individual offers, campaigns or compact web presences where a clear message matters more than unnecessary scope.',
          command: 'web --landing --responsive --fast',
          features: ['Compact onepager or purpose-built landing page', 'Distinct responsive design instead of a standard template', 'Fast, clean technical foundation'],
          ctaLabel: 'Start a project',
        },
        {
          title: 'Web Presence',
          price: 'from €950',
          badge: 'Recommended',
          featured: true,
          claim: 'Being found is only the beginning.',
          description: 'For businesses and brands that want to build trust, guide users and turn attention into real inquiries.',
          command: 'web --brand --content --conversion',
          features: ['Thoughtful structure for services, content and contact', 'Visual system aligned with brand and audience', 'User journeys built for engagement and conversion'],
          ctaLabel: 'Plan web presence',
        },
        {
          title: 'Business App',
          price: 'from €1,650',
          claim: 'When software needs to start taking work off your plate.',
          description: 'For internal tools, dashboards and custom web applications that digitize or automate real processes.',
          command: 'app --data --roles --automation',
          features: ['Interfaces designed around real workflows', 'Roles, forms, data, APIs and automation', 'Maintainable architecture built for growing functionality'],
          ctaLabel: 'Discuss application',
        },
      ],
    },
};
